### ISSUE TITLE
Crashes when I try to create new app folder

### ISSUE THREAD

**Issue by kouros17** [Maestroschan/appfolders-manager-gnome-extension#9] opened 2017-06-04 23:23 UTC
I'm using manjaro, installed from [here](https://extensions.gnome.org/extension/1217/appfolders-manager/), but crashes when I try to create new app folder if I don't start typing the name immediately . 

![appfolders-manager-gnome-extension](https://cloud.githubusercontent.com/assets/27904795/26766219/b732ad64-4995-11e7-9a92-915fb1ccf0be.gif)

**Comment by maoschanz** [comment] 2017-06-05 10:44
it's not an actual crash, it just closes the menu against your will ;)

Like i said in the comments you read on extensions.gnome.org, there is here a new version for almost a week, which solve this issue. It has just been published this morning, please try to upgrade the extension.

**Comment by pkomur** [comment] 2017-06-05 19:37
I confirm this issue with the latest version. I can't use upper letters during writing folder name. New app folder name window closes, when I use Shift key.

**Comment by kouros17** [comment] 2017-06-05 20:15
Thank you @Maestroschan, it's fixed with newer version. :+1:

**Comment by maoschanz** [comment] 2017-06-05 22:08
> I confirm this issue with the latest version. I can't use upper letters during writing folder name. New app folder name window closes, when I use Shift key.

Exact, however that is an other issue
The dialog closes stupidly when the backspace key is pressed, too :(

Meanwhile, i suggest to copy-paste the name you need.

**Comment by maoschanz** [comment] 2017-06-05 22:34
Fixed, i just uploaded the new version on the official website

**Comment by kouros17** [comment] 2017-06-08 00:34
I go to the official website but it looks like it has not been upgraded yet.

**Comment by maoschanz** [comment] 2017-06-08 17:46
When i upload a version, it doesn't mean it is published. Publication of updates are done by moderators once a week (approximatively)

**Comment by kouros17** [comment] 2017-06-21 05:54
O.k I did the upgrade while ago and I confirm that issue is fixed.:)

**Comment by maoschanz** [comment] 2017-06-21 07:40
Nice, i close it then.

(I said "once a week (approximatively)", it looks like i was too optimistic)

**Closed as completed** 2017-06-21 07:40 UTC
Labels: bug

**Comment by fawtytoo** [comment] 2019-01-20 23:38
I tried the latest commit, but this issue remains in Gnome 3.22

**Comment by maoschanz** [comment] 2019-01-21 02:06
The code from june 2017 has nothing in common with the current code so i'm not sure people here are concerned. The issue doesn't "remain", it's a new one, so please open a new one.

And give details:

- the current code doesn't even provide an entry in the context menu, so what is the problem?
- is it a focus issue? only visually (cursor not blinking but typing possible) or actually (typing not possible at all) ?
- is it a crash? if yes, run `sudo journalctl -f /usr/bin/gnome-shell` in a terminal to have logs

**Comment by fawtytoo** [comment] 2019-01-21 11:33
Perhaps the issue isn't persistent, but it could be a regression. My issue exactly matches that of the OP. Selecting "+ NewAppFolder" does nothing.

Journal logs:

> Jan 21 11:30:49 debian gnome-shell[1205]: JS ERROR: Error: Value is not a valid 64-bit integer
                                          _patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:32
                                          _patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:41
                                          AppfolderDialog<._buildCategoriesSection@/home/steve/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/appfolderDialog.js:204
                                          wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                          AppfolderDialog<._init@/home/steve/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/appfolderDialog.js:54
                                          wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                          _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
                                          Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
                                          createNewFolder@/home/steve/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:301
                                          injectionInAppsMenus/injections._redisplay</</a<@/home/steve/.local/share/gnome-shell/extensions/appfolders-manager@maestroschan.fr/extension.js:81

**Comment by maoschanz** [comment] 2019-01-21 12:05
>My issue exactly matches that of the OP. 

As i said, it doesn't, it can't match the issue of the OP, which was about a focus problem concerning a text entry (the entry was in the menu, and the menu was closed when trying to focus the entry). This text entry doesn't even exist anymore.

Your new issue will be #58
