### ISSUE TITLE
New AppFolders not created when right-clicking on applications -- Arch Linux Rolling

### ISSUE THREAD

**Issue by jrodd96** [Maestroschan/appfolders-manager-gnome-extension#92] opened 2020-01-14 03:33 UTC
After installing extension in Arch Linux Rolling (Anarchy Linux), no errors are displayed and the install appears successful.

However, when right-clicking on applications in the overview and selecting `Add To > + New AppFolder` nothing happens. Otherwise, I can add applications to the two existing AppFolders in overview. I am just unable to add any new AppFolders. 

The extension settings also have nowhere to create new AppFolders as well.

**Comment by maoschanz** [comment] 2020-01-14 12:17
duplicate of #88 and #91

**Comment by maoschanz** [comment] 2020-01-14 12:17
(closed for the same reason as these issues)

**Closed as completed by maoschanz** 2020-01-14 12:17 UTC
Labels: bug, duplicate, wontfix
