### ISSUE TITLE
Can't rename or add AppFolder on GNOME 3.34.1

### ISSUE THREAD

**Issue by rauhapaev** [Maestroschan/appfolders-manager-gnome-extension#99] opened 2020-01-27 14:33 UTC
Hello, after I updated GNOME to 3.34.1, now when I want to add a new AppFolder, the menu just closes so I can't add the new folder. Also when I try to rename existing one by right-clicking, the rename menu didn't appear.

OS: Pop! OS 19.10
GNOME: 3.34.1
Kernel: 5.3.0-7625-generic

**Comment by maoschanz** [comment] 2020-01-27 15:13
Duplicate of #88 #91 #92: as stated in the readme, this extension doesn't support GNOME Shell 3.33 and higher since these versions can manage appfolders natively

**Closed as completed by maoschanz** 2020-01-27 15:13 UTC
Labels: duplicate, invalid
